### ISSUE TITLE
[Q] (Where i can find last source?)

### ISSUE THREAD

**Issue by zonalimitatore** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1105]
Where i can find the source,for the last update? (3 days ago)?
Thanks

**Comment by oldman4U** [comment]
Hi.

Could you please help the community to keep the repositories usable by closing the other tickets you opened before and which you probably do not need anymore. Thank you

You should find the source here:

![Screenshot 2020-09-19 at 13 36 23](https://user-images.githubusercontent.com/54359396/93666338-b3a4cf00-fa7d-11ea-99ad-fdb502a533bf.png)

**Comment by zonalimitatore** [comment]
Maybe stay open because are not solved?

**Comment by zonalimitatore** [comment]
Anyway...There is no last source

**Comment by oldman4U** [comment]
I meant this ticket which you have not answered since July 21st:
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/334
If a question is not answered, there is no need to close the ticket. But it is unfriendly to ignore other users and not to answer them.

Here is the link to the firmware which has been released 4 days ago.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/archive/master.zip

Please let me know if this answers your question or if you need any additional help.
Thank you

**Comment by zonalimitatore** [comment]
old ticket close. ( sorry,i forget)

ive  download latest but the files arent update. only the .bin is,and not the entire folder.
i mean that i can flash the newest firmware,but cant mod it,because the source files are old.

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/93688485-7ca6db80-fac6-11ea-8322-985e29f7ba31.png)

**Comment by zonalimitatore** [comment]
Yeah...open it

**Comment by oldman4U** [comment]
Thank you for closing the old ticket. 

Could radek8 show you the right source? Thanks radek8

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/93689990-07da9e00-fad4-11ea-962c-dd58941d1d99.png)

**Comment by oldman4U** [comment]
@zonalimitatore 

Could you please reply or close this ticket in case you do not need it anymore.

Thank you

**Comment by oldman4U** [comment]
@zonalimitatore

Please help the community to keep this system useful and close all tickets which are not needed anymore.

Thank you

**Comment by oldman4U** [comment]
Thank you
