### ISSUE TITLE
[FR] Add the ability to rotate screen by 90 as well not only 180

### ISSUE THREAD

**Issue by Atanasovgoran** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1160]
I am making a "pocket" sized printer, and I am using an SKR Mini board and TFT24 V1.1 for the electronics.
And it makes more sense in the design to put the display in vertical rather than horizontal (90 degrees rotation)

Or is there a way to make it already, but I guess it would be somewhat complicated since menu items would need to be repositioned.

Thanks

**Comment by oldman4U** [comment]
Hi.

Please read the other Feature Requests related to Vertical screen orientation and close the ticket in case you believe this is already covered.

Please also keep in mind that this open source project only works because of the community and therefore also people like you and me working together to make this happen

Thank you

**Comment by Atanasovgoran** [comment]
> Hi.
> 
> Please read the other Feature Requests related to Vertical screen orientation and close the ticket in case you believe this is already covered.
> 
> Please also keep in mind that this open source project only works because of the community and therefore also people like you and me working together to make this happen
> 
> Thank you

My bad, searched for 90 degree and not vertical. I see they teased it but so far no release.

Closing the ticket.

**Comment by oldman4U** [comment]
Thank you and happy printing.

Atanasovgoran <notifications@github.com> schrieb am Do. 8. Okt. 2020 um
13:57:
