### ISSUE TITLE
Zoffset menu issue : the nozzle dives into the bed after modifications on hotend

### ISSUE THREAD

**Issue by Chukozor** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1364]
I have TFT35 3.0, I like the Zoffset menu which enables to live test it, but I think it would be great to add some safety option. What I mean is that if the Zoffset is at the moment of -3mm and if I make some changes on the carriage and need something like a -2.8 Zoffset the nozzle will dive into the bed by 0.2mm (-2.8 -(-3)) before I can add the 0.2mm to the Zoffset on this menu. So it's a serious problem here. Actually what I do now is that I send some Gcode to change the Zoffset because of that issue, and then tune it with the actual menu of the TFT.

I propose to add an option in the Zoffset tune menu to change directly before launching the {homing+G1 Z0}, and then tune it like it's actually made.

**Comment by oldman4U** [comment]
Hi.

So this is a feature request, right?

@digant73 Is this your "area" and something where you could add your experience as a user and developer, please?

Thank you

**Comment by digant73** [comment]
once some PRs will be merged and reviewed I will try to have some time for an improvement

**Comment by oldman4U** [comment]
This would be great digant73, thank you.

So I add this to the FR list.

**Comment by CBDesignS** [comment]
Please do not shoot the messenger here. but I think this kind of question or a one very close to the topic was asked in the marlin git or maybe a "trusted website" a good long time ago and their short and blunt " as they usually are" answer was if you adjust anything related to hotend, nozel or Z you MUST start from scratch with any z offset and recalibrate from Z0. I like the idea of a safe offset as I use a glass bed but I could imagine a random newbie to printing changing a nozel and buring it into the glass and smashing it whereas if they had to start from z0 (the long way) there is less chance of this happening and they learn how to do it "correctly" instead of guestimating how much difference there might be. it takes seconds to zero and adjust the offset with paper using the tft as is

**Comment by Chukozor** [comment]
To be honest following your reasoning it's then stupid to name it a "Zoffset tuning menu", just rename it "decrease Zoffset menu" then that would make more sense because you can only decrease it if you "do the things as they are meant to be". @CBDesignS

**Comment by Chukozor** [comment]
to be accurate : a nozzle which dives in the bed by even 0.01mm is still a nozzle diving in the bed !

**Comment by digant73** [comment]
@oldman4u this was a bug that I fixed in PR 1379. So this bug/FR must be removed from the list
