### ISSUE TITLE
[BUG] (MBL - No Mesh Saved - No Mesh In Editor)

### ISSUE THREAD

**Issue by ETE-Design** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1377]
When using Manual Mesh Bed, before you have to choose what slot to save to, and you could even edit the mesh from the TFT, with newest version - Compiled Today 12/12-2020 you don't have the possibility to choose what slot to save to, and the Mesh Editor just show a screen with no dots and then freeze, so when start printing no mesh is used.

**Comment by digant73** [comment]
different bugs were provided by one of the last PR. Restoring my previous code, the map is available again and there is no freeze. However due to other changes on other API, the screen is not refreshed in case of popup. Also the navigation cursor does not work properly.
I was working on a FR for Z offset menu, I will restore part of my code (working properly), but it will be needed work on other API to fix the bugs introduced on that API.

**Comment by ETE-Design** [comment]
@digant73 With your code will it also be possible to again choose what slot to save the mesh to? Or is it just saved in Slot 0 cause you don't need others with MBL?
Yeah it is fustrating that someone tell you to do one thing, and then others dosen't... Is the working code on your Github? Cause right now MBL is broken :-(

**Comment by digant73** [comment]
MBL didn't have a slot to select. It is UBL only.
I'm just creating a PR with the fix to Mesh Editor.
I will add then a FR on taht PR

**Comment by ETE-Design** [comment]
@digant73 Still same problem, Seem's like it dosen't save the Mesh No matter What I try to do... As you can see at the picture it says Off even egen I enabled BL: On, and still freeze at the Mesh...
![IMG_20201212_215140](https://user-images.githubusercontent.com/15981309/101994697-90786d00-3cc4-11eb-94e2-c73f528ddecd.jpg)
![IMG_20201212_215113](https://user-images.githubusercontent.com/15981309/101994701-953d2100-3cc4-11eb-977d-152e3f1c99ca.jpg)

**Comment by radek8** [comment]
I use bilinear leveling and I have the same problem.

**Comment by ETE-Design** [comment]
@radek8 Did not solve the problem for MBL :-(
