### ISSUE TITLE
[FR] Review of encoding and representation of Characters in the language files and the font files

### ISSUE THREAD

**Issue by MarkusThur** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1963]
**Is your feature request related to a problem? Please describe.**
This request is related to #1952.

There definitely at least with the BTT 70" is a encoding issue with the language headers and inis in combination with the provided fonts.

language header files and .ini files are or should be encoded UTF-8

according to the readme.md in the fonts file contain character representations  encoded ASCII
or UTF-16. 

> The "byte_ascii.fon" is the bitmap fonts of ASCII, size: 12*24
> The "word_unicode.fon" is the bitmap fonts of UTF-16, size: 24*24
> Scan direction: form UP to DOWN, from LEFT to RIGHT

Sadly I can't check the .fon files, as I don't know the proper editor for them. From testing those files contain a proper representation of U-2103 &#x2103;

For the first 127 characters of the Unicode this is fine, for the higher characters this in some way must and does fail.

Sure is correct UTF-8 encoded 2 characters representation of &#xB0;&#x43; does work, one character representation of &#x2103; does work also if encoded in correct UTF-8 encoding `0xe2 0x84 0x83`.
The "weak" encoding mixing the UTF-16 encoding ´0x2103` into the UTF-8 language files to represent &#x2103;, like found in the german .ini and header file, does interestingly work in some environments, while fails in others. 

**Describe the solution you'd like**

- Indicating clearly the needed UTF-8 encoding of language_xx.ini files and language_xx.h files by adding a markdown README.md in the respective folders mentioning it. 

**Describe alternatives you've considered**
- implementing a autocheck in the `buildroot/scripts/auto_gen_language_pack.py` to ensure the correct encoding of critical characters like U-2103 would be great, but in my eyes it's not a priority.
- Processing of \uxxxx escape sequences instead of deleting them in `buildroot/scripts/auto_gen_language_pack.py` would be great
- Providing a proper editor for the fonts / explaining the .fon file format better in order to identify a proper editor.  (in progress, see answer to #1957) 

**Additional context**
Thank you for reading and considering this

**Comment by guruathwal** [comment]
@MarkusThur The character `℃` is being properly encoded in both language_xx.ini and language_xx.h file for all languages. 
The UTF-8 encoding is already implemented in `buildroot/scripts/auto_gen_language_pack.py`. 
I inspected all the files and found that all unicode characters are being encoded correctly (see image below). If there was an issue with the firmware then it will be with all the TFT variants because the API is the same for all the variants. the only difference is the screen resolution.
It is not clear what kind of problem you are having with just the `℃` character and why? Did you modify any part of the firmware? You need to share the file which has improper encoding and share a photo of the display with the issue.

![image](https://user-images.githubusercontent.com/22422544/120638448-be798580-c48d-11eb-8dfb-5504402e54de.png)

**Comment by MarkusThur** [comment]
Some files contained the UTF-16 / Windows 1252 encoding of it `21 03` at some point, somewhere at the Vx.x.27 tag. This happens as the files do not contain a encoding indicator and the editor "guesses" the encoding wrong.

Lets have a markdown file at the relevant positions to remind on the right encoding and everything is fine.
If the auto_gen_language_pack.py would automatically take care of it, would be really great.
