### ISSUE TITLE
[Request] BLTouch support

### ISSUE THREAD

**Issue by Titi9237** [bigtreetech/BIGTREETECH-TouchScreenFirmware#20]
Hi,

Is there a plan to get a BLTouch/3DTouch support with the screen ?

Regards

**Comment by DustyProp** [comment]
Bump ^ U was wondering the same thing. I would like to be able to use the home button and have it run the home with the BLTouch, not run off the edge of my bed and low enough to crack the glass if I let it go with out power cycling the printer. Good thing I have a pi that will run the G28; G29.

**Comment by spilz87** [comment]
@Titi9237 The idea is to add buttons to reset/retract/down the bltouch ?

**Comment by DustyProp** [comment]
Then why bother having the auto home button as part of the firmware? I don't see the point if adding buttons was the main design feature.

**Comment by spilz87** [comment]
@DustyProp for me it’s different needs as you have on marlin lcd 
Homing + leveling as automatic is a “good” button.
Resolve an issue with bltouch without returning to lcd12864 mode can be a good idea, more over when we know that changing mode affect Marlin (because of using rotary encoder and because returning to touchscreen send G-code to marlin and init SD card)

**Comment by Titi9237** [comment]
> @Titi9237 The idea is to add buttons to reset/retract/down the bltouch ?

Yes, it could be useful to add these buttons to the "homing screen".

**Comment by spilz87** [comment]
Actually it’s not too difficult, the real need is icons

**Comment by guruathwal** [comment]
@Titi9237 BLtouch feature has been added through PR #87 . You can close the issue now.
