### ISSUE TITLE
Open letter for Bigtreetech

### ISSUE THREAD

**Issue by kisslorand** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2685]
This is an open letter to @bigtreetech.
This repository doesn't offer the ability to report a user to the owner of the repository, I had no other choice to file a complaint about the user "digant73" than to make an open letter.

Here's what's all about:

I am protesting here about the attitude and behaviour of the user "digant73". For a year now he was constantly harassing me in almost  every pull request I made, under the pretext of various imaginary super-rules and not backed-up theories. Behaved like he would be some boss of me. It took some time but I learned how to ignore this aggression and to move on. Two months ago this attitude suddenly stopped, it gave me a mouth of fresh air and the mood to make some pull requests to fix bugs and come with innovations. This quietness had a short lifespan... 
After this calm before the storm he (digant73) took it to the next level. He started a new harassment type. He started to make pull request where he included many changes from unmerged pull requests of mine. Nothing Earth-shaking but enough to bother me that my work is hijacked. He has a history of doing so in the past too. It started with copying changes from another unmerged pull request with the excuse of "keeping pull requests in sync". At least he mentioned where are the codes "borrowed" from. It didn't happened many times so I moved on.
   That changed when he made a pull request purely on a code I shared with him in one of our private discussion over Skype. It is about PR #2233. From the history of this PR's description it can be seen that at first he gave me no credit at all for the "Updated clock for MKS TFT", it was done only later, after I opposed about it in private. The discussions where I provide him the idea and the code itself and my disapproval about sharing my idea and taking credit for it can be seen on the screenshots I took from Skype.

Me sharing my work:
![72MHz Shared_1](https://user-images.githubusercontent.com/50251547/213936891-d945902c-6c33-48cb-8925-aa532759de4b.jpg)

Me opposing to the theft of my work:
![72MHz Shared_2](https://user-images.githubusercontent.com/50251547/213936949-09d74737-01ee-4eb3-8ef0-ebb13e247976.jpg)

  I have to mention that I deliberately contacted him in private and not in public, even if I was very upset that he stole my idea and work and also took credit for it, I still didn't wanted to humiliate him in public.

This wasn't the end of it. After stopping the aggressive harassment in every one of my ongoing pull request he got inventive, started a new type of aggression by copy & paste parts of code from my unmerged PRs. First was PR #2630 . I highlighted there the parts that were copied from my work so others to be aware of it too, he (digant73) tried to hide my comments by marking as "resolved" my complaints. It continues with PR #2674 and PR #2678.
He (digant73) is not stopping there, he went further by "borrowing" a whole idea from one of my unmerged pull request. It is PR #2607  where I identified a bug and fixed it. In the description of that PR the said bug is described properly and how the bug is fixed by that pull request is explained also.
There was a ticket opened (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2640) by a user where in a response I pointed out clearly that the issue is known and already fixed by PR #2607. 
Now comes "digant73" and makes a pull request (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2679) that is supposedly fixing the same issue by "borrowing" the same idea of fixing it from my pull request. The issue was identified already, the cause of it was identified already, a fix was provided already, someone reported the issue and he already got the answer that it has been taken care of, yet "digant73" came up magically with a solution for an already identified and fixed bug. The fix he provided is based on the same idea than my pull request, namely to treat the "M524" gcode command as an emergency command and send it directly to the motherboard avoiding the queue. Even if his implementation is a crippled down and a prone to bugs version of mine, it was me who found the issue, the cause of it and the fix for it. He (digant73) copy & pasted again from me. 
In an effort to invalidate my pull request, to be sure his "borrowed" work has more chances to be merged, PR #2679 was closed and the changes made there were included in another pull request (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2678). Since this pull request started as a great addition, the chances of being merged together with the idea "borrowed" from me are higher and it will invalidate my work.
The copy & paste campaign "digant73" is conducting is not only taking away from me the time needed to write a code, it also takes away the time spent to find the cause of the bug, the time spent making tests for the best and most reliable fix for it. It makes this repository a hostile environment for me.
One other thing worth mentioning about the attitude of the user "digant73" is that despite his demand from other users to respect all the rules, even the rules that are not written and he made them up, he defies requests of this very repository owner. Particularly this one:
"We recommend creating separate PRs for unrelated fixes, do not gather them in one single PR. By doing so it will make it easier for our team to focus on eventual issues and to review them."
It's written in the file "coding_standard.md" in this very repository.

I am respectfully asking the owner of this repository to convince user "digant73" to stop harassing me or anybody else by any means, explain him that contributing to any Github repository is not a contest, there are no winners, there are no prizes, everyone is doing it for free sometimes taking time off from family and friends. Please also explain him that he is just a regular user as the rest of us, he is not above anybody, behaving in good manners is not optional. Thank you!

**Comment by digant73** [comment]
@kisslorand
Try to be honest please, you are going to continue with this ridiculous film just to force at any cost a merge of not one, not two but all your PRs. Please, have a break with such kind of extortions and blackmails!
I have no more extra time to spend with you on a never ending story. If and when there is something to really fix or improve, we can provide them independently by your blackmails!
You could ask directly on our bigtreetech's chat for clarification about your PRs avoiding your embarrassing drama!
The better suggestion I con provide you is just to have a break if the effort on this project became an obsession more than a collaborative hobby.
There is a common contradiction in all of your soap operas:
* From one side you expect that no one can even sync a bunch of meaningless comments (I would eventually complain if they were different) from your PRs (waiting to be merged since more than 4 months now) or to simply provide a bug fix without the need of an external Emergency module. Internal (handled only by TFT) emergency commands are already existing (used for M600, onboard pause etc...) but as usual, you prefer to adapt the code to what you want to sell more than adopting an already existing common logic (e.g. used for M600, remote pause, purge more etc...).
* On the other side, you have no consideration at all for any kind of collaboration even when it has been asked more and more times in the past but you continue also to re-submit the same PRs more times. Some examples? just the PRs you mentioned. What have been asked by me in #2607 or #2591 or by me and another contributor in #2601 and what was your reply? Was it collaborative? Did you realize that I avoided to apply any kind of rework on the code originally made by you (e.g. comment module, extrude and load/unload menu) although I could really improve it?
Not to mention your complaint about 72Mhz (changed only the freq multiplier) added after almost one year just to finally have code in sync. Please, give the proper weight to the things and you will live more in harmony.
