### ISSUE TITLE
BLT offset wizzard when homing is with limiters 

### ISSUE THREAD

**Issue by Grzesinski** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2741]
I've been changing nozzles a lot lately and noticed that the BLT offset wizard (from the TFT touchscreen) is not working properly.
It should be noted that in my printer homing is performed with Z end-stop, BLTouch is used to correct the bends of the table only.
The whole procedure proceeds as expected, but the calibration result is incorrect.

### Steps to reproduce
1. Manually set any reasonably BLT offset (optionally)
2. Run BLT offset wizzard
3. Check result and compare it with Marlin ofset wizzard

**Expected behavior**
TFT BLT Wizzard offset should gives results similar as Marlin Wizzard .

**Actual behavior**
The whole procedure proceeds as expected (homing, testing), but the calibration result is incorrect.
The Marlin BLT offset wizard calibration gives a result of about -2.5mm and this is the correct value, verified on many printouts.
The calibration result from the FTF display gives strange, incorrect results (-0,x -1,xmm, etc.). 
The end result of the wizard depends on the current stored BLT offset, which should not be the case.

### Hardware Variant
SKR MINI E3 V2.0 (TMC2209)
TFT35 E3 V3.0 + SKR MINI E3 V2.0 (TMC2209)
Endstop homing + BLTouch

TFT Firmware Version & Main Board Firmware details
BIGTREE_TFT35_V3.0_E3.27.x (2023-01)
Marlin 2.1.2 (2023-01)

### Discussed in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/discussions/2733

**Comment by digant73** [comment]
try to change the value for parameter "probing_z_offset" in config.ini (e.g. set it to 1).

**Comment by digant73** [comment]
Yes, I provided that param because I also had a similar issue in one of my printers. I previously opened a bug report on Marlin repo and info about the offsets applied here and there by Marlin were provided but at the end it was more a bug in Marlin side than something wrong in TFT fw. At the end (for the issue I had in my printer) I could solve the issue in TFT fw with that workaround (enabling probing after homing with endstop). But is seems it is not enough for you or something was changed in Marlin now. I will try to find and link here my PR (it should report also the link of the discussion on Marlin repo).
Probably it is better to report your issue on Marlin repo just for an update about the logic applied by Marlin now

**Comment by Grzesinski** [comment]
Does this feature work for you?
I use Marlin 2.1.2 (2023-01) due to TFT FW requirements.
The changes to the config files have been synced with my previous builds. I also made the changes required by the latest release of TFT FW.
In Marlin, BLT z-offset calibration works fine.

**Comment by digant73** [comment]
yes it was but I don't have that printer (setup) now.
Do you remember if it was working for you in the past (before you upgraded Marlin and/or TFT fw to latest versions)?
Do you also use Home Offset in your setup?

**Comment by Grzesinski** [comment]
Unfortunately, the feature also failed in my previous build Marlin 2.0.9.1+TFT (2022-02).
I was hoping the new version was fixed.
I don't have any Home Offsets (M206) set.
I will check #2742 today.  TFT FW update required?

**Comment by digant73** [comment]
Ok. I will check in the future if your issue could be fixable in TFT side (it is more related to info not available to TFT).
