### ISSUE TITLE
TFT35 v2.0 + encoder

### ISSUE THREAD

**Issue by Buggins77** [bigtreetech/BIGTREETECH-TouchScreenFirmware#293]
Good afternoon, tell me please.  I ordered Tft 35 v2.0 ... I later noticed that there is v 3.0 with an encoder and two control modes.  Can I now order a separate encoder for this board, since I saw a connector for it on version 2.0?  Or will it not work like that (mean with two modes)?  (for information - SKR 1.4 motherboard) Regards Anton

**Comment by guruathwal** [comment]
no not possible. V2 does not have the required EXP connection sockets.

**Comment by Buggins77** [comment]
Ok, then why there is a ENCODER input on board, beside USART3?

**Comment by bkzspam** [comment]
> Ok, then why there is a ENCODER input on board, beside USART3?
> and one more question, as i have understand, with this mode, i can only send G-code command via touch screen, but what about feedback between motherboard ant TFT?
> Does some there info what possibility i can get using V2.0?

I think it's possible. Since encoder port is already available. You just need to find out Mosi, Sck and may one more pin for LCD_PINS_RS. But for full functionality you should find out more available pin. And some digging around the code. 

Of course there is feedback available. Otherwise you won't be able to get temperature (and kinda) information. For testing it simply you can send M117 gcode with a message like "M117 TFT" then a message will pop-up in the screen that says "TFT". This screen is nice, it has bugs. It should has a bit more function. But it's open source! Which is lead to me buy this screen against the MKS's screen.

**Comment by bigtreetech** [comment]
Hello, LCD 12864 mode needs a hardware SPI to read the ST7920 timing sent by Marlin and parse & draw point on the TFT,  but TFT35 V2.0 no pin out hardware SPI, So usually, TFT35 V2.0 only has Touch Scren mode, no 12864 mode
