### ISSUE TITLE
[FR] IDEA: smart preheat icons

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [bigtreetech/BIGTREETECH-TouchScreenFirmware#364]
@guruathwal

please consider migration to "smart preheat icons":
* use generic non-named icons for buttons
* use different colors for preheat icon background
* use icon text image overlay with nozzle/hotbed temperature values

for example:

#### section in config.ini
```
#
# setup warmup temperature
#
[heater_preset]

preheat_1_label  = PLA
preheat_1_hotbed = 61
preheat_1_nozzle = 201

preheat_2_label  = PEG
preheat_2_hotbed = 71
preheat_2_nozzle = 251

preheat_3_label  = ABS
preheat_3_hotbed = 101
preheat_3_nozzle = 231

preheat_4_label  = NYL
preheat_4_hotbed = 111
preheat_4_nozzle = 261

preheat_5_label  = PEK
preheat_5_hotbed = 121
preheat_5_nozzle = 281
```

#### result menu structure

![IMG_20200306_154305](https://user-images.githubusercontent.com/1622151/76125357-44c0c680-5fc2-11ea-9912-21ba0350aed6.jpg)

#### working prototype
firmware : 
* [custom-marlin/DISK](https://github.com/random-builder/bigtree-tft-code/tree/custom-marlin/DISK)

sources
* [custom-marlin/TFT/src/User/Menu/HeaterPreset.c](https://github.com/random-builder/bigtree-tft-code/blob/custom-marlin/TFT/src/User/Menu/HeaterPreset.c)

**Comment by guruathwal** [comment]
I also suggested a similar idea when the Preheat feature was added https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/95#issuecomment-552299539, but I am not in favor this anymore for adding buttons which do not have any major function because we have only 8 Megabytes of flash storage of which more than 50% is already filled up.
This is the reason I switched to List mode in the Settings menu and Custom G-code Menu.

I plan to integrate the Preheat menu with the Manual heating menu, but it will take some time.
