### ISSUE TITLE
[FR] Custom Icon Pack Helper?

### ISSUE THREAD

**Issue by Hukuma1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#418]
Sorry I don't know how to do PRs. D:

Wanted to update the photo examples of the icon UIs here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

I made the assets in native resolution for my TFT35 (480x320, thanks @guruathwal!) so these images  are 200% upscaled. I only have the main menu screen, but if there's interest maybe I'll work up the whole menu topology for icon pack making ease.

**Classic UI**
![BTTclassicUI](https://user-images.githubusercontent.com/54511555/77016371-ad9a2e00-6934-11ea-9e57-23c2ab2cad58.png)

**Unified Modern UI**
![BTTmodernUI](https://user-images.githubusercontent.com/54511555/77016415-d3273780-6934-11ea-8c61-a184fa55b420.png)

**Peter Mann/Acenotass Icons** (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/412)
![BTTpetermanacenotass](https://user-images.githubusercontent.com/54511555/77016502-08cc2080-6935-11ea-8f3e-29bf2182e220.png)

Btw I could not locate these icons, @thisiskeithb: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/374#issuecomment-597282516 Do you have a link?

**Comment by thisiskeithb** [comment]
They were in a Facebook post a while ago and aren’t compatible with the latest classic UI since icons need to be created.

Keeping multiple icon packs up to date here (assuming they can be included under GPL V3) and working for each UI will be the biggest challenge if that’s the direction you want to head in.

**Comment by Hukuma1** [comment]
Ah I see. No, I was just thinking of linking to a few that were maintained. Seemed like there was a bunch scattered all around. This way people have a choice and the creators get the most exposure by being seen on the official page.

**Comment by thisiskeithb** [comment]
Congratulations on your first contribution 🙂 https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/421

I've updated the readme to use the above previews for Classic & Unified UIs.

**Comment by Hukuma1** [comment]
Thank you sir! :)

Btw @guruathwal as I was making this UI grid from scratch I noticed the Unified graphic of InfoBox.bmp was 1 pixel longer possibly? Or did I goof my math somewhere? It's currently 215x95 for TFT35. Should be maybe 214?

![pixelpeeping](https://user-images.githubusercontent.com/54511555/77106380-391aca00-69dc-11ea-84b8-5f533162210e.png)

**Comment by guruathwal** [comment]
@Hukuma1 
The correct gap between the icons is calculated as:
Icon spacing = [ Screen_Width - (Icon_width*4) ] / 4
Icon spacing = [480-(95*4)]/4
Icon spacing = 25

Left & Right spacing will be = Icon Spacing/2 = 12.5
But there is no half pixel. So The LCD will place the first icon at 12px. Due to this, all the icons are shifted to the left side by 1 pixel.

**Comment by Hukuma1** [comment]
Guess I should have asked before making it! Lesson I'll never learn. ;) Is the top and bottom spacing also 12? Thanks for all the info.
