### ISSUE TITLE
[BUG] BaudRate.bmp icon does not update SW V25.3

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#466]
### Description

BaudRate.bmp icon does not update SW V25.3

![BaudRate](https://user-images.githubusercontent.com/44540957/77684339-0cf6de80-6fc4-11ea-8cca-30baa79aa761.png)

### Steps to reproduce
Updated as usual

**Expected behavior**

The icon does not update, it remains from the previous firmware.

### Additional Information

Who can check how the icons are updated in the new version?
[TFT24 Iconpack 'The Round Miracle' by Acenotass for v25.3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4389247/TFT24.Iconpack.The.Round.Miracle.by.Acenotass.for.v25.3.zip)
[TFT28 Iconpack 'The Round Miracle' by Acenotass for v25.3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4389251/TFT28.Iconpack.The.Round.Miracle.by.Acenotass.for.v25.3.zip)
[TFT35 Iconpack 'The Round Miracle' by Acenotass for v25.3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4389252/TFT35.Iconpack.The.Round.Miracle.by.Acenotass.for.v25.3.zip)

**Comment by guruathwal** [comment]
Yes, because the name of the icon **BAUDRATE** is being changed to **115200** during compiling due to this line:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/d85c40439d314d7e3fef6eaaae6093c82a9fcd11/TFT/src/User/Configuration.h#L93

this is now fixed in #464 
I have also improved the icon update process to display errors.
