### ISSUE TITLE
Display update error

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#616]
I want to signal a very annoying bug. When I start printing a file. I click on the file. Then, after the print screen appears, the hotend and hotbed temperatures are not shown on the display. Specifically, it does not update while heating the hotend or hotbed. Is there anything you can do about it?

**Comment by Grrby** [comment]
I can confirm. I observe exactly the same bug and nothing has changed since several firmware versions. Temperatures are not updated until printing starts.

Another thing is huge lag in reaction. For example from touching Stop to real stop printing its about 20s. Stop button is mostly for some emergency situation and now is useless. But this is another topic.

**Comment by AntoszHUN** [comment]
Then we are waiting for the repair. Or see if we get info from someone. :)

**Comment by guruathwal** [comment]
This is not a bug. This is a Marlin Firmware issue because of **M109** & **M190** G-codes.
The **Marlin Firmware** gets stuck in a wait loop with these commands and waits for the temperature to reach the target. While in the wait loop it will not respond to any command until the temperature reaches the target or by sending **M108** to break the loop, which needs `EMERGENCY_PARSER` to be enabled in **Marlin Firmware**.
Because of this, the TFT will not receive any new temperature info and it will keep showing the last temperatures it received before the wait loop.

https://marlinfw.org/docs/gcode/M109.html

![image](https://user-images.githubusercontent.com/22422544/80389810-365ba080-88c9-11ea-8ba2-d4fc84bfdcea.png)

**Comment by Grrby** [comment]
Thank you very much for explanation.

**Comment by AntoszHUN** [comment]
Thanks for the reply! So does that mean you can't do that? I have EMERGENCY_PARSER turned on. Or should I turn it off? What's better?

**Comment by guruathwal** [comment]
@AntoszHUN keep it turned on.

**Comment by AntoszHUN** [comment]
That's right. Thanks!
