### ISSUE TITLE
BMPs NAMED INCORRECTLY ACCORDING TO LIST

### ISSUE THREAD

**Issue by colinjohnm** [bigtreetech/BIGTREETECH-TouchScreenFirmware#631]
BMP FILES INCORRECTLY NAMED IN TFT35 BMP UNIFIED

STATUSNOZZLE
STATUSBED
STATUSFAN
 should be STATUS_NOZZLE
STATUS_BED
STATUS_FAN
 According to LIst

So Fail to Load and leave front screen incomplete

Hope this helps

**Comment by NAPCAL** [comment]
Since the renaming these files it has caused an issue with currently compiled .bin updates because those still use the old file names. So most users end up with this. 
![77AE6E81-AA80-4D8D-B341-58405F8534D4](https://user-images.githubusercontent.com/47440988/81121972-8ce26380-8ef5-11ea-8271-b15cd727b646.jpeg)

**Comment by NAPCAL** [comment]
Since the renaming these files it has caused an issue with currently compiled .bin updates because those still use the old file names. So most users end up with this.
