### ISSUE TITLE
[BUG] Preheat buttons 2 & 3 (PETG and ABS by default) are not working

### ISSUE THREAD

**Issue by creamywhite** [bigtreetech/BIGTREETECH-TouchScreenFirmware#675]
Preheat buttons (Menu - Heat/Fan - Preheat) number 2 and 3 (PETG and ABS by default) are not working. They do not set any heating targets for hotend/bed/both after clicking them. As a note, first one (PLA) works as intended for hotend/bed/both.

**Comment by SonBroku** [comment]
Confirm, I'm also having this issue. I'm gonna take a looksee and see what I can find, if there's anything obvious. I'll let you know if I come up with anything.

**Comment by SonBroku** [comment]
Okay, it's actually working, but it's a bit finicky. When I tap so that the bottom icon says "both" and tap PETG, it will start heating both the nozzle and bed, but not until I back out of that menu. 

Then when I go back into the menu, it behaves totally differently. It seems like the entire implementation of that menu is kind of weird and buggy.  I would say you're correct in that the PLA button mostly behaves as normal, but the PETG and ABS ones DO work, they're just...kind of weird.

**Comment by creamywhite** [comment]
@SonBroku , I'm unable to make them work like you've described.

**Comment by roomme13** [comment]
in my build, that button work fine, but the label is screw-up.
![photo_2020-05-12_00-05-07](https://user-images.githubusercontent.com/1905950/81589976-4eacde80-93e4-11ea-99aa-3b21b40fdd3b.jpg)

**Comment by creamywhite** [comment]
@roomme13 , had that problem too (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/664) - somehow, rebuilding the FW and reloading the config helped. However, I don't know if all preheat buttons worked for me when their labels were mangled like that - didn't test it then.

**Comment by roomme13** [comment]
I just build this one recently, 2 or 3 hours ago. Same result, maybe I should try it one more time.
In my case that just label, the function itself work  normally.
Thank you by the way.
