### ISSUE TITLE
[Q] a lot of open issues

### ISSUE THREAD

**Issue by traffic-light** [bigtreetech/BIGTREETECH-TouchScreenFirmware#968]
There are a lot open issues and double feature requests

Maybe it's a good idea to close all bugs/ questions that are older then / no reply after 2 months?

Most of them are not relevant since some updates and so on.

**Comment by Tygrys-1** [comment]
IMHO this project lacks coordination. Or kind of leadership. Or even the consistent vision of it's future. @bigtreetech ?

**Comment by traffic-light** [comment]
In my opinion it's not really something to blame bigtreetech for.
They've got more things to do.

Maybe it's an idea for them to add moderators. Some active users that would like to help them with this 
(If that is possible)

**Comment by Tygrys-1** [comment]
Not to blame anyone, it is opensource, it is free to modify for ones purposes, it is overall a good piece of the software, but the freedom of doing anything might become a nightmare ;-)

IMHO a mess in the reported issues is only a part of the wider thing.

**Comment by traffic-light** [comment]
I agree with that.

**Comment by oldman4U** [comment]
Hi.

I agree 100%

If you check this repository as well as some others (all reps of hardware which i also use) you will find many tickets where i asked the owner to close it because it is outdated, or hardware issue related or just an old issue which is already fixed. In case the owner did not answer, I asked BTT to close it, like this is done by Scott for the Marlin repo. Unfortunately BTT does not react, so i gave up on this.

Without removing unneeded tickets, the ticket system will become unusable very soon. This has nothing to do with Open Source but with the owner of a repository.

**Comment by traffic-light** [comment]
It seems to be that @bigtreetech is closing old tickets.
Good job @bigtreetech !

**Comment by oldman4U** [comment]
@bigtreetech 

What can i do that you close unneeded tickets also in other repositories?

Down to less than 150 tickets from more than 200 is great but can only be the beginning. The goal should be approximately 20 open tickets per repo - i believe.
